alias which='alias | /usr/bin/which --tty-only --read-alias --show-dot --show-tilde'
alias grep='grep --color=auto'
alias bfg='java -jar "/c/Users/yuz899/Google Drive/_env/bfg.jar"'
alias la='ls -a'
alias ll='ls -l'
